import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import playerRoutes from './player.routes.js';
import coachRoutes from './coach.routes.js';
import clubRoutes from './club.routes.js';
import agentRoutes from './agent.routes.js';
import mediaRoutes from './media.routes.js';
import searchRoutes from './search.routes.js';
import shortlistRoutes from './shortlist.routes.js';
import offerRoutes from './offer.routes.js';
import negotiationRoutes from './negotiation.routes.js';
import kycRoutes from './kyc.routes.js';
import evaluationRoutes from './evaluation.routes.js';
import subscriptionRoutes from './subscription.routes.js';
import paymentRoutes from './payment.routes.js';
import advertisementRoutes from './advertisement.routes.js';
import notificationRoutes from './notification.routes.js';
import contactRoutes from './contact.routes.js';
import adminRoutes from './admin.routes.js';
import settingsRoutes from './settings.routes.js';
import miscRoutes from './misc.routes.js';

export const routes = Router();

routes.use('/auth', authRoutes);
routes.use('/me', userRoutes);
routes.use('/players', playerRoutes);
routes.use('/coaches', coachRoutes);
routes.use('/clubs', clubRoutes);
routes.use('/agents', agentRoutes);
routes.use('/media', mediaRoutes);
routes.use('/search', searchRoutes);
routes.use('/shortlists', shortlistRoutes);
routes.use('/offers', offerRoutes);
routes.use('/negotiations', negotiationRoutes);
routes.use('/kyc', kycRoutes);
routes.use('/evaluations', evaluationRoutes);
routes.use('/subscriptions', subscriptionRoutes);
routes.use('/payments', paymentRoutes);
routes.use('/advertisements', advertisementRoutes);
routes.use('/notifications', notificationRoutes);
routes.use('/contacts', contactRoutes);
routes.use('/admin', adminRoutes);
routes.use('/settings', settingsRoutes);
routes.use('/', miscRoutes);
