export const sportsOptions = [
  { label: "كرة اليد", value: "handball" },
  { label: "كرة السلة", value: "basketball" },
  { label: "الكرة الطائرة", value: "volleyball" },
  { label: "الريشة الطائرة", value: "badminton" },
  { label: "ألعاب القوى", value: "athletics" },
  { label: "التنس", value: "tennis" },
  { label: "كرة الطاولة", value: "table_tennis" },
  { label: "الكاراتيه", value: "karate" },
  { label: "التايكوندو", value: "taekwondo" },
  { label: "السهام", value: "darts" },
  { label: "الرياضات الالكترونية", value: "esports" },
  { label: "السباحة", value: "swimming" },
  { label: "الجودو", value: "judo" },
  { label: "المبارزة", value: "fencing" },
  { label: "الدراجات الهوائية", value: "cycling" },
  { label: "الإسكواش", value: "squash" },
  { label: "رفع الأثقال", value: "weightlifting" },
  { label: "كرة قدم الصالات", value: "futsal" },
  { label: "الملاكمة", value: "boxing" },
  { label: "الجمباز", value: "gymnastics" },
  { label: "البلياردو والسنوكر", value: "billiards_snooker" },
  { label: "المصارعة", value: "wrestling" },
];
